services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3333:3333" # Mapeia a porta 3000 do container para a porta 3000 do host
    networks:
      - meucrediario-bridge
    environment:
      - DB_HOST=db # Nome do serviço do banco de dados no docker-compose
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=meucrediario
    depends_on:
      - db # Define a dependência do serviço do banco de dados

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapeia a porta 3000 do container para a porta 3000 do host
    networks:
      - meucrediario-bridge
    depends_on:
      - backend # Define a dependência do serviço do banco de dados

  db:
    image: postgres:latest
    restart: always
    networks:
      - meucrediario-bridge
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meucrediario
    ports:
      - "5432:5432" # Mapeia a porta 5432 do container para a porta 15432 do host
    volumes:
      #- ./meucrediario.app.sql:/docker-entrypoint-initdb.d/meucrediario.app.sql
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  meucrediario-bridge:
    driver: bridge
